### ISSUE TITLE
Add support for templating app.yaml files

### ISSUE THREAD

**Issue by jprobinson** [NYTimes/drone-gae#11]
Currently, there is no way of injecting secrets into the environment of `gcloud app deploy` commands via the CLI.

We should add a 'vars' and an `app_template` to the config that allows folks to declare a pass key/value pairs into a templateed app.yaml file.

**Comment by usererror** [comment]
@jprobinson When you say config do you mean the GAE type?

**Comment by jprobinson** [comment]
Yes! I'm actually working on this right now 👍  any input is appreciated

**Comment by usererror** [comment]
Gotcha. Happy to pair on it with you if you're up for it.

**Comment by jprobinson** [comment]
I'll tag you for review, for sure.
