### ISSUE TITLE
Feature: Add a `max_versions` configuration option to use in deployments

### ISSUE THREAD

**Issue by jprobinson** [NYTimes/drone-gae#46]
If supplied with a non-zero value along with the "deploy" action, after the deployment completes successfully, the plugin would _delete_ any older versions beyond the "max version" count.

For example, if we added `max_versions: 2` to deployment config and the deployed service had 4 total versions after the deployment completed, the plugin would remove the 2 older versions.

This is meant to deal with the [limit of 210 versions for an App Engine project](https://cloud.google.com/appengine/docs/standard/go111/an-overview-of-app-engine#limits), which can be reached rather quickly if a large/active team is developing against the project. At the moment, reaching this 210 limit causes the plugin to error and developers must manually remove older versions from their projects. This should remove that manual intervention without requiring users to add any more moving parts to their deployment pipelines.

**Comment by saranrapjs** [comment]
Presumably this would start deleting anything over `max_versions` at the oldest version? e.g. chronologically sorted?

**Comment by jprobinson** [comment]
Correct, I'd think we'd cron-sort the versions and drop the oldest.
